tuberous = require '../'
potato = require 'potato'

CONFIGURATION = 
    db: 'tuberous-test'
    host: '127.0.0.1'
    port: 27017

assert = require "assert"

MyModel = tuberous.Model
    static:
        CONFIG:
            safe: true
        collectionName: 'People'
    components:
        firstname: potato.String
        lastname: potato.String

describe 'tuberous', ->
    
    before (done)->
        tuberous.configure CONFIGURATION, done

    it 'makes it possible to write a model', (done)->
        obj = MyModel.make()
        obj.setData
            firstname: 'Paul'
            lastname: 'Masurel'
        assert.ok obj._id?, "The object should have an autogenerated id"
        assert.equal obj.__potato__.collectionName,'People'
        obj.save ->
            MyModel.findById obj._id,(err, entry)->
                assert.equal err, undefined
                assert.equal entry.firstname, 'Paul'
                assert.equal entry.lastname, 'Masurel'
                done()

    after (done)->
        tuberous.close done
